### ISSUE TITLE
Spatial tab

### ISSUE THREAD

**Issue by muleytracker** [ndow-wisr/telemetR#2]
When displaying points with Brownian Bridge, Kernel, or MCP's overlayed, you can't identify (display date/time info) on points within the polygons. Maybe have a check box to either "bring forward" points to be on top of polygons, or have a way to uncheck the polygons temporarily to select individual points and show the timestamp info.

**Comment by kissmygritts** [comment]
Due to how the map is created. Base map, then points and lines, then polygons.
