### ISSUE TITLE
Create Sample Collars.csv and Animals.csv

### ISSUE THREAD

**Issue by ghost** [ndow-wisr/telemetR#29]
Hi

great app! Are sample files for Collars.csv and Animals.csv public available too? 

thx
Christof

**Comment by kissmygritts** [comment]
I've been meaning to get some sample data. I'll likely pull sample data from existing `adehabitat` or movebank.org at some point. 

Long term I plan on better generalizing the app. Right now it is very specific to our needs.

**Comment by kissmygritts** [comment]
@ckluss check this release for a working example of the system.
